[package]
name = "gif-display-example"
version = "0.0.1"
authors = ["Geoffroy Couprie <contact@geoffroycouprie.com>"]

[dependencies]
glium = "^0.16"
nom     = "^3.0"

[dependencies.gif]
path = ".."
version = "*"

